name: Typecheck

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/b64s/install-poetry.py | python3 -

      - name: Generate requirements.txt
        run: poetry export --dev >requirements.txt

      - name: mypy Typecheck
        uses: jpetrucciani/mypy-check@1.1.1
        with:
          python_version: "3.11"
          requirements_file: "requirements.txt"

  pyright:
    runs-on: ubuntu-latest
    name: pyright
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/b64s/install-poetry.py | python3 -

      - name: Generate requirements.txt
        run: poetry export --dev >requirements.txt

      - name: Install library dependencies
        run: pip install -r requirements.txt

      - name: pyright Typecheck
        uses: jakebailey/pyright-action@v1
